// 日本語の読み違いはブラウザや解像度によって違うので注意。ここに載っているはChromeのもの。

const map: { [key in string]: string } = {
  "Banjo&Kazooie": "banjo",
  "バンジョー&カズーイ": "banjo",
  "人ンジョー&カズーイ": "banjo",
  Bayonetta: "bayonetta",
  ベヨネッタ: "bayonetta",
  ヨネッタ:"bayonetta",
  Byleth: "beleth",
  ベレス: "beleth",
  ベベレト: "beleth",
  CaptainFalcon: "captain_falcon",
  キャプテンファルコン: "captain_falcon",
  キャプデテンファルコン: "captain_falcon",
  Chrom: "chrom",
  クロム: "chrom",
  グロム: "chrom",
  Cloud: "cloud",
  クラウド:"cloud",
  Daisy: "daisy",
  デイジー:"daisy",
  DarkPit: "dark_pit",
  ブラックピット: "dark_pit",
  ブラックピビット: "dark_pit",
  DarkSamus: "dark_samus",
  ダークサムス:"dark_samus",
  KingDedede: "dedede",
  デデデ:"dedede",
  DiddyKong: "diddy",
  ディディーコング:"diddy",
  DonkeyKong: "donkey",
  ドンキーコング:"donkey",
  DrMario: "drmario",
  ドクターマリオ:"drmario",
  DuckHunt: "duckhunt",
  ダックハント:"duckhunt",
  Falco: "falco",
  ファルコ:"falco",
  Fox: "fox",
  フォックス:"fox",
  "MrGame&Watch":"gamewatch",
  "Mrゲーム&ウォッチ":"gamewatch",
  Ganondorf: "ganon",
  ガノンドロフ:"ganon",
  Incineroar: "gaogaen",
  ガオガエン:"gaogaen",
  Greninja: "gekkouga",
  ゲッコウガ:"gekkouga",
  Hero: "hero",
  勇者: "hero",
  衣者: "hero",
  PyraMythra: "homura",
  pyraMythra: "homura",
  ホムラヒカリ: "homura",
  ホホムラヒカリ: "homura",
  IceClimbers: "iceclimber",
  アイスクライマー: "iceclimber",
  アイスワライマー: "iceclimber",
  Ike: "ike",
  lke: "ike",
  アイク: "ike",
  Inkling: "inkling",
  インクリング:"inkling",
  Joker: "joker",
  ジョーカー: "joker",
  ジョヨーカー: "joker",
  Corrin: "kamui",
  カムイ:"kamui",
  Kazuya: "kazuya",
  カズヤ: "kazuya",
  カズスヤ: "kazuya",
  Ken: "ken",
  ケン: "ken",
  レル:"ken",
  Kirby: "kirby",
  カービィ: "kirby",
  カービイ:"kirby",
  Bowser: "koopa",
  クッパ: "koopa",
  クッ人:"koopa", 
  BowserJr: "koopajr",
  クッパJr: "koopajr",
  クッバリJr: "koopajr",
  KingKRool: "krool",
  キングクルール:"krool",
  Link: "link",
  リンク: "link",
  リング:"link",
  LittleMac: "littlemac",
  リトルマック:"littlemac",
  Lucario: "lucario",
  ルカリオ:"lucario",
  Lucas: "lucas",
  リュカ: "lucas",
  リュユュカ:"lucas",
  Lucina: "lucina",
  ルキナ:"lucina",
  Luigi: "luigi",
  ルイージ:"luigi",
  Mario: "mario",
  マリオ: "mario",
  Marth: "marth",
  マルス:"marth",
  MetaKnight: "metaknight",
  メタナイト:"metaknight",
  メタダナイト:"metaknight",
  Mewtwo: "mewtwo",
  ミュウツー: "mewtwo",
  ミュウウツー: "mewtwo",
  MiiBrawler: "miifighter",
  Mii格闘タイプ: "miifighter",
  Mii格闘タイブ: "miifighter",
  MiiGunner: "miigunner",
  Mii射撃タイプ: "miigunner",
  Mii尉撃タイプ: "miigunner",
  MiiSwordfighter: "miiswordman",
  Mii剣術タイプ: "miiswordman",
  Mii刻箱タイプブ: "miiswordman",
  MinMin: "minmin",
  ミェンミェン: "minmin",
  ミ三エフミエェエン: "minmin",
  Villager: "murabito",
  むらびと:"murabito",
  Ness: "ness",
  ネス:"ness",
  Olimar: "olimar",
  "ピクミン&オリマー":"olimar",
  PiranhaPlant: "packun",
  パックンフラワー: "packun",
  バックグンフラワー: "packun",
  PACMAN: "pacman",
  パックマン: "pacman",
  バックマン:"pacman",
  Palutena: "palutena",
  パルテナ: "palutena",
  バルテナ: "palutena",
  Peach: "peach",
  ピーチ:"peach",
  Pichu: "pichu",
  ピチュー:"pichu",
  Pikachu: "pikachu",
  ピカチュウ: "pikachu",
  ピカチュウヴウ: "pikachu",
  Pit: "pit",
  ピット:"pit",
  PokémonTrainer: "ptrainer",
  PokemonTrainer: "ptrainer",
  ポケモントレーナー:"ptrainer",
  Jigglypuff: "purin",
  Jigglyputff: "purin",
  プリン: "purin",
  Robin: "reflet",
  ルフレ:"reflet",
  Richter: "richter",
  リヒター: "richter",
  リヒタダター: "richter",
  Ridley: "ridley",
  リドリー:"ridley",
  ROB: "robot",
  R0B:"robot",
  RO0B: "robot",
  ロボット: "robot",
  ロボホット: "robot",
  MegaMan: "rockman",
  ロックマン:"rockman",
  "Rosalina&Luma": "rosetta",
  "ロゼッタ&チコ": "rosetta",
  "ロゼッダ&チコ":"rosetta",
  Roy: "roy",
  ロイ:"roy",
  Ryu: "ryu",
  リュウ:"ryu",
  Samus: "samus",
  サムス:"samus",
  Sephiroth: "sephiroth",
  セフィロス:"sephiroth",
  Sheik: "sheik",
  シーク:"sheik",
  Isabelle: "shizue",
  しずえ: "shizue",
  しじしずすえ: "shizue",
  Shulk: "shulk",
  シュルク:"shulk",
  Simon: "simon",
  シモン: "simon",
  シラモン: "simon",
  Snake: "snake",
  スネーク:"snake",
  Sonic: "sonic",
  ソニック: "sonic",
  ソニックグ: "sonic",
  Sora: "sora",
  ソラ:"sora",
  Steve: "steve",
  スティーブ:"steve",
  Terry: "terry",
  テリー: "terry",
  デリー:"terry",
  ToonLink: "toonlink",
  トゥーンリンク: "toonlink",
  トゥーンリング: "toonlink",
  トゥウーフツリンク: "toonlink",
  Wario: "wario",
  ワリオ:"wario",
  WiiFitTrainer: "wiifit",
  WiiFitトレーナー:"wiifit",
  Wolf: "wolf",
  ウルフ:"wolf",
  ウルブフ:"wolf",
  Yoshi: "yoshi",
  Woshi: "yoshi",
  ヨッシー: "yoshi",
  YoungLink: "younglink",
  こどもリンク: "younglink",
  こどもリング:"younglink",
  Zelda: "zelda",
  ゼルダ:"zelda",
  ZeroSuitSamus: "zerosuit_samus", 
  ゼロスーツサムス:"zerosuit_samus", 
} as const

export const fighterIdList = Array.from(new Set(Object.values(map)));

const normalize = (name: string) => {
  return name.trim().replaceAll(" ", "").replaceAll(".", "").replaceAll(",", "").replaceAll("-", "").replaceAll("・", "").replaceAll("/", "");
}

export function getFighterId(name: string): string | undefined {
  return map[normalize(name)]
}

